name = "worker-china-consult-proxy-prod"
main = "src/index.ts"
compatibility_date = "2024-09-19"

account_id = "3e6a373891514e0d6c52b79395032f86"
workers_dev = false

# Define your routes here
route = "https://consult.cybersight.org.cn/*"

# Environment for testing in development/staging
[env.qa]
name = "worker-china-consult-proxy-qa"
route = "https://qa74-consult.cybersight.org.cn/*"

[env.local]
route = "https://consult.cybersight.org.cn/*"

[observability]
enabled = true